before_script:
  - REPO="$(echo $TRAVIS_REPO_SLUG | cut -d'/' -f2)"

script: 
  - echo Generating zip file for plugin $REPO
  - mkdir $REPO
  - rsync -Rr . ./$REPO/
  - rm -rf ./$REPO/$REPO ./$REPO/.git
  - zip -r $TRAVIS_BUILD_DIR/$REPO.zip $REPO
  - unzip -l $REPO.zip

deploy:
  provider: releases
  api_key:
    secure: iZXdDviXX6IK0A7kJBBr0E5GIC6IZluoPD1n5QtQWT+/zuRUvKGgN/P4UwwQipMt3XOn07e2ddPshGQbMtcL02RL2Cx1MooYPOfdUD+w9ybK4LJFKPRDvX92Vc6gRc5F5dj2OtsoSsF0wC1mMar+Z23LygAAbbKidjzTsZFeks8dfvcCST2m6dXEwRVJSCpYHSlSCvziQuG9Eb9C4xpDwKywqcmddFLjqa8zcvFWwVBPhoZ8bNeQl9k/ViY3jNV6uJ+ujuk3Ut5zE+DIYC98mPg2cCGWecHDCxA5dqNyc9aUEdxaqMyPIggm/RTAEjnS861O36B6bYkHd477LYw4w4ArMo15c5UHlT8XVnBzzptbWTP97XVrLQsU5JLqoxXLbwPmmyGHwWNFq1Ts+2oXJSnaYNTT6b+UFvxB8m3quRhPydpRG0tN2xwyaWd40A7rwRBeIrOLbqdngrhKAzB8sKg7R5uU/xpG38YG5/b7PmNhOMx0Ao+7xSRqCX82j7cyEQaIM7GrXIg8GVpKSBMDp9Ui2wLWwTTBSY/gR9VAkuRWu6tWtFth5Zr1fw9Sck6U/eLDBuA52JW1JN7y2P+8hXxVUPmcMw2Agl1pGOfgN46owhM5TU0HzrDPOGJNzLFF2sZi7QuaGFsqO0frkYUtjJJhkSzJyOkRiTb0Vb6cY38=
  file: "$TRAVIS_BUILD_DIR/cf7-pushover-notify.zip"
  skip_cleanup: true
  on:
    tags: true